import type { ParcoursContent } from './types';

export const asthmeParcours: ParcoursContent = {
  slug: 'asthme',
  title: 'Asthme',
  subtitle: 'Controler, respirer, vivre pleinement',
  description: '21 jours pour mieux controler votre asthme.',
  icon: 'bronches',
  proInstrument: 'koos-ps',
  proIntro: "Quel degre de difficulte avez-vous pour les activites suivantes, a cause de votre asthme ?",
  days: [
    { day: 1, theme: "Comprendre votre asthme", phase: 'comprendre',
      content: { title: "L'asthme : des bronches hypersensibles", body: "L'asthme est une maladie chronique ou les bronches sont enflammees et reagissent de maniere excessive aux stimuli.\n\n**Les 3 mecanismes :**\n- Inflammation chronique de la paroi des bronches\n- Contraction des muscles autour des bronches (bronchospasme)\n- Production excessive de mucus\n\nL'asthme bien controle permet une vie NORMALE - y compris le sport de haut niveau.\n\nLe controle repose sur : traitement de fond quotidien, eviction des declencheurs, autogestion.", keyMessage: "L'asthme bien controle = vie normale. Le traitement de fond est la cle.", source: "GINA 2024" },
      action: { title: "Verifier votre controle - 4 questions", description: "Dans les 4 dernieres semaines : 1) Symptomes diurnes > 2x/semaine ? 2) Reveil nocturne ? 3) Bronchodilatateur de secours > 2x/semaine ? 4) Limitation d'activite ? Si OUI a 1-2 : partiellement controle. Si OUI a 3-4 : non controle.", duration: "3 min" },
    },
    { day: 2, theme: "Le traitement de fond", phase: 'comprendre',
      content: { title: "L'inhalateur quotidien : votre bouclier", body: "**Le corticoide inhale (CSI)** est le traitement de base de l'asthme.\n\n**Regle absolue : NE JAMAIS L'ARRETER sans avis medical.**\n- Meme quand vous allez bien\n- L'arret -> retour de l'inflammation\n- Les doses inalees sont minuscules\n\n**Technique d'inhalation :**\n80% des patients n'utilisent pas correctement leur inhalateur.\n\nDemandez a votre pharmacien de verifier votre technique pendant la cure.", keyMessage: "Le traitement de fond NE S'ARRETE PAS quand ca va bien. Verifiez votre technique.", source: "GINA 2024, Cochrane Inhaler technique" },
      action: { title: "Verifier votre technique d'inhalation", description: "Prenez votre inhalateur et demandez au pharmacien ou au medecin de verifier votre technique. 80% des patients font au moins une erreur.", duration: "5 min" },
    },
    { day: 3, theme: "Facteurs declenchants", phase: 'comprendre',
      content: { title: "Identifier VOS declencheurs", body: "Chaque asthmatique a ses propres declencheurs :\n\n**Allergenes :** acariens, pollens, poils d'animaux, moisissures\n**Irritants :** tabac, pollution, parfums forts\n**Effort :** asthme d'effort (voir J8)\n**Infections :** rhume, grippe\n**Meteo :** air froid et sec\n**Stress :** modifie la reactivite bronchique\n**Medicaments :** aspirine, AINS, betabloquants\n\nTenez un journal des symptomes 1 semaine.", keyMessage: "Identifiez VOS declencheurs. Chaque asthmatique est different.", source: "GINA 2024" },
      action: { title: "Journal des declencheurs - J1", description: "Notez : symptomes (lesquels, quand), activite au moment, meteo, stress. Continuez 7 jours.", duration: "3 min" },
    },
    { day: 4, theme: "Le plan d'action", phase: 'comprendre',
      content: { title: "Votre plan en 3 zones (vert, orange, rouge)", body: "**Zone verte (controle) :**\n- Pas de symptomes quotidiens\n- Activites normales\n-> Continuez le traitement de fond\n\n**Zone orange (aggravation) :**\n- Symptomes plus frequents\n- Bronchodilatateur de secours > 2x/semaine\n-> Doublez le CSI + secours\n-> Si pas d'amelioration en 48h -> consultez\n\n**Zone rouge (crise severe) :**\n- Essoufflement au repos, difficulte a parler\n- Bronchodilatateur peu efficace\n-> 15/112 IMMEDIATEMENT\n\nCe plan doit etre ECRIT et connu de vos proches.", keyMessage: "Vert = continuez. Orange = augmentez le traitement. Rouge = 15/112.", source: "GINA 2024, HAS Asthme" },
      action: { title: "Ecrire votre plan 3 zones", description: "Notez les criteres vert/orange/rouge et les actions pour chaque zone. Montrez-le a un proche.", duration: "10 min" },
    },
    { day: 5, theme: "Exercice et asthme", phase: 'comprendre',
      content: { title: "L'exercice ameliore l'asthme", body: "Contrairement a une idee recue, l'exercice est BENEFIQUE pour l'asthme (Cochrane 2023).\n\n**L'asthme d'effort :**\n- Touche 70-80% des asthmatiques non controles\n- Se manifeste 5-10 min apres un effort intense\n- PREVENTION : 2 bouffees de bronchodilatateur 15 min avant + echauffement progressif\n\nDes champions olympiques sont asthmatiques. L'asthme n'interdit AUCUN sport quand il est bien controle.", keyMessage: "L'exercice ameliore l'asthme. Bronchodilatateur + echauffement avant l'effort.", source: "Cochrane Exercise Asthma 2023, GINA 2024" },
      action: { title: "Marche progressive - 10 min", description: "Echauffement : 2 min tres lent. Puis 6 min a rythme modere. Puis 2 min ralenti. Si asthme d'effort : 2 bouffees de secours 15 min avant.", duration: "10 min" },
    },
    { day: 6, theme: "Cure thermale et asthme", phase: 'comprendre',
      content: { title: "L'air thermal pour vos bronches", body: "La cure thermale pour l'asthme repose sur :\n- L'inhalation d'eau thermale (humidifie et apaise les bronches)\n- L'aerosoltherapie (microparticules thermales en profondeur)\n- L'exercice en air humide et chaud\n\nL'environnement thermal est pauvre en allergenes et en pollution - un repit pour vos bronches.\n\nProfitez de la cure pour stabiliser votre asthme et verifier votre technique d'inhalation.", keyMessage: "L'air thermal humide apaise les bronches. Profitez-en pour stabiliser votre controle.", source: "Thermal respiratory evidence" },
      action: { title: "Respiration consciente en cure", description: "Pendant votre soin d'inhalation : inspirez nez 4s, expirez bouche 6s. L'eau thermale penetre mieux quand vous respirez lentement.", duration: "5 min" },
    },
    { day: 7, theme: "Bilan semaine 1", phase: 'comprendre',
      content: { title: "Ce que vous avez appris", body: "Semaine 1 !\n\n- L'asthme bien controle = vie normale\n- Le traitement de fond NE S'ARRETE PAS\n- Identifiez VOS declencheurs (journal)\n- Plan d'action 3 zones\n- L'exercice AMELIORE l'asthme\n\nSemaine 2 : exercice adapte, gestion des crises, environnement.", keyMessage: "Traitement de fond + plan d'action + exercice = le triangle du controle.", source: "Synthese GINA/HAS" },
      action: { title: "Bilan journal declencheurs", description: "Relisez votre journal de la semaine. Identifiez 1-2 declencheurs recurrents.", duration: "5 min" },
      hasMiniPro: true,
      quiz: [
        { question: "Faut-il arreter le traitement de fond quand on va bien ?", options: ["Oui, c'est gueri", "Non, jamais sans avis medical", "Oui, en ete"], correctIndex: 1, explanation: "Le traitement de fond maintient le controle. L'arret provoque le retour de l'inflammation." },
        { question: "L'exercice est-il bon pour l'asthme ?", options: ["Non, il declenche des crises", "Oui, il ameliore les symptomes", "Seulement la marche"], correctIndex: 1, explanation: "L'exercice regulier ameliore la capacite respiratoire et reduit les symptomes (Cochrane 2023)." },
      ],
    },
    { day: 8, theme: "Exercice adapte asthme", phase: 'agir',
      content: { title: "Bouger en securite", body: "**Avant l'effort :** 2 bouffees bronchodilatateur si asthme d'effort + echauffement 5-10 min\n**Pendant :** respirez par le nez si possible. Levres pincees si essouffle. Intensite moderee.\n**Apres :** recuperation progressive 5 min.\n\n**Sports recommandes :** natation, marche, velo, yoga.\n\nSi crise pendant l'effort : STOP -> secours -> position assise -> si pas mieux 15 min -> 15/112.", keyMessage: "Echauffement progressif + bronchodilatateur avant = sport en securite.", source: "GINA 2024" },
      action: { title: "Circuit - 15 min", description: "Echauffement 3 min marche lente + 8 min marche moderee + renforcement (levers chaise 8x, montee 10 marches) + recuperation 4 min.", duration: "15 min" },
    },
    { day: 9, theme: "Environnement interieur", phase: 'agir',
      content: { title: "Votre maison : alliee ou ennemie ?", body: "**Anti-acariens :** housses anti-acariens (matelas + oreiller), lavage draps 60C/semaine, pas de moquette, aspirateur HEPA.\n**Anti-moisissures :** VMC, aerer 10 min/jour, pas de sechage linge en interieur.\n**Anti-irritants :** pas de tabac (JAMAIS), produits menagers sans parfum, pas de bougies/encens.\n**Animaux :** si allergie confirmee -> animal hors de la chambre.", keyMessage: "La chambre doit etre un sanctuaire : housses anti-acariens, pas de moquette, pas de tabac.", source: "GINA 2024" },
      action: { title: "1 changement chez vous", description: "Identifiez 1 amelioration (housses anti-acariens, arret encens/bougies, produit menager sans parfum).", duration: "5 min" },
    },
    { day: 10, theme: "Technique respiratoire", phase: 'agir',
      content: { title: "Respiration nasale et Buteyko", body: "**Respiration nasale :**\nLe nez filtre, rechauffe et humidifie l'air. Respirez par le nez au quotidien.\n\n**Technique Buteyko simplifiee :**\n- Inspirez nez 3s\n- Expirez nez 3s\n- Pause : retenez 3-5s (leger manque d'air)\n- Repetez 10 cycles\n\nCette technique reduit l'hyperventilation frequente chez les asthmatiques.", keyMessage: "Respirez par le nez. L'air nasal est filtre, chaud et humide - vos bronches l'adorent.", source: "Buteyko evidence, GINA 2024" },
      action: { title: "Respiration nasale - 5 min", description: "Nez uniquement : inspir 3s, expir 3s, pause 3s. 10 cycles. Si vous ne pouvez pas respirer par le nez, signalez-le a votre medecin.", duration: "5 min" },
    },
    { day: 11, theme: "Allergies et asthme", phase: 'agir',
      content: { title: "Le lien allergie-asthme", body: "70-80% des asthmatiques ont une composante allergique.\n\n**Actions :**\n- Identifier vos allergenes (tests cutanes)\n- Eviction ciblee (acariens, pollens, animaux)\n- Antihistaminique si rhinite allergique associee\n- Desensibilisation si allergie documentee\n\nTraiter la rhinite ameliore l'asthme : le nez et les bronches sont un seul systeme ('united airways').", keyMessage: "Traiter le nez ameliore les bronches. Nez et poumons = meme systeme.", source: "GINA 2024, ARIA" },
      action: { title: "Bilan allergique", description: "Avez-vous fait des tests allergiques ? Si non, notez-le pour votre medecin. Si oui, relisez vos resultats.", duration: "5 min" },
    },
    { day: 12, theme: "Gerer une crise", phase: 'agir',
      content: { title: "Que faire quand ca siffle", body: "**Crise legere-moderee :**\n1. Position assise, calme\n2. Bronchodilatateur de secours : 4-6 bouffees\n3. Attendez 15-20 min\n4. Si amelioration -> doublez le traitement de fond, consultez 24-48h\n5. Si pas d'amelioration -> 4-6 bouffees supplementaires + medecin\n\n**Crise severe (15/112) :**\n- Essoufflement au repos, ne peut pas parler\n- Bronchodilatateur peu efficace\n- Levres bleues\n- Confusion", keyMessage: "4-6 bouffees -> 15 min -> reevaluer. Levres bleues ou phrase impossible = 15/112.", source: "GINA 2024" },
      action: { title: "Ecrire le protocole de crise", description: "Notez : 1) Assis. 2) 4-6 bouffees. 3) 15 min. 4) Reevaluer. 5) Si echec -> medecin/15. Collez-le dans votre cuisine.", duration: "5 min" },
    },
    { day: 13, theme: "Stress et asthme", phase: 'agir',
      content: { title: "Le stress contracte vos bronches", body: "Le stress est un declencheur reel de l'asthme. Il modifie la reactivite bronchique et favorise l'hyperventilation.\n\n**Techniques :**\n- Coherence cardiaque : inspir nez 4s, expir nez 6s, 5 min\n- Respiration nasale consciente (J10)\n- Exercice physique regulier\n- Yoga (combine mouvement + respiration)", keyMessage: "Le stress contracte les bronches. Coherence cardiaque + yoga = relachement.", source: "GINA 2024" },
      action: { title: "Coherence cardiaque - 5 min", description: "Inspir nez 4s, expir nez 6s. 5 minutes. Respiration nasale uniquement.", duration: "5 min" },
    },
    { day: 14, theme: "Bilan semaine 2", phase: 'agir',
      content: { title: "Mi-parcours", body: "Deux semaines !\n\n- Exercice en securite\n- Environnement interieur optimise\n- Respiration nasale maitrisee\n- Protocole de crise affiche\n\nVotre controle s'est-il ameliore ?", keyMessage: "Mi-parcours. Le controle s'ameliore avec la regularite.", source: "Synthese" },
      action: { title: "Exercice complet - 15 min", description: "Echauffement 3 min + marche 8 min + renforcement + recuperation 4 min.", duration: "15 min" },
      hasMiniPro: true,
      quiz: [
        { question: "Combien de bouffees de secours en cas de crise ?", options: ["1 bouffee", "4-6 bouffees", "10 bouffees"], correctIndex: 1, explanation: "4-6 bouffees de bronchodilatateur de secours, attendre 15 min, reevaluer." },
      ],
    },
    { day: 15, theme: "Plan post-cure", phase: 'consolider',
      content: { title: "Votre programme", body: "**Post-cure :**\n- Traitement de fond QUOTIDIEN\n- Exercice 30 min/jour (echauffement + bronchodilatateur si besoin)\n- Plan 3 zones affiche\n- RDV allergologue/pneumologue annuel\n- Vaccination grippe annuelle", keyMessage: "Traitement de fond + exercice + suivi medical = controle durable.", source: "GINA 2024" },
      action: { title: "3 objectifs", description: "Ex : 'Exercice 5x/semaine', 'RDV pneumo dans 3 mois', 'Housses anti-acariens'.", duration: "5 min" },
    },
    { day: 16, theme: "Voyage et asthme", phase: 'consolider',
      content: { title: "Voyager sereinement", body: "**Checklist voyage :**\n- Traitement de fond + secours en cabine (JAMAIS en soute)\n- Ordonnance en anglais (DCI) si voyage a l'etranger\n- Assurance rapatriement\n- Altitude > 2500m : prudence\n- Reperer les urgences locales", keyMessage: "Medicaments en cabine, ordonnance en DCI, assurance rapatriement.", source: "GINA 2024 travel" },
      action: { title: "Preparer une trousse voyage", description: "Rassemblez : inhalateur de fond + secours + ordonnance + carte urgence asthme.", duration: "5 min" },
    },
    { day: 17, theme: "Sport et asthme", phase: 'consolider',
      content: { title: "Tous les sports sont possibles", body: "**Excellents :** natation, marche, velo, yoga, tai-chi.\n**Tres bien :** course (avec echauffement), danse.\n**Adaptes :** sports d'endurance intense (bronchodilatateur + echauffement long).\n\nDes athletes olympiques sont asthmatiques. L'asthme n'interdit aucun sport quand il est bien controle.", keyMessage: "Aucun sport interdit si asthme controle. Echauffement + bronchodilatateur = cle.", source: "GINA 2024" },
      action: { title: "Tester une activite", description: "Essayez une activite nouvelle avec echauffement 5 min + bronchodilatateur si besoin.", duration: "20 min" },
    },
    { day: 18, theme: "Alimentation", phase: 'consolider',
      content: { title: "Manger pour vos bronches", body: "**Preuves moderees :**\n- Regime mediterraneen (fruits, legumes, poisson)\n- Omega-3\n- Vitamine D\n- Poids raisonnable (le surpoids aggrave l'asthme)\n\n**Attention :** certains asthmatiques sont intolerants aux sulfites (vin, fruits secs). Notez si vous suspectez un lien.", keyMessage: "Poids raisonnable + mediterraneen. Attention aux sulfites si sensible.", source: "GINA 2024" },
      action: { title: "1 changement", description: "Fruits/legumes a chaque repas. Poisson 2x/semaine.", duration: "5 min" },
    },
    { day: 19, theme: "Rhinite et polypes", phase: 'consolider',
      content: { title: "Le nez : la porte d'entree", body: "80% des asthmatiques ont une rhinite associee. Traiter le nez ameliore l'asthme.\n\n**Traitements du nez :**\n- Lavage nasal quotidien (serum physiologique)\n- Corticoide nasal en spray (fluticasone, mometasone)\n- Antihistaminique si rhinite allergique\n\nLes polypes nasaux sont parfois associes a l'asthme severe. Si vous avez perdu l'odorat -> signalez-le.", keyMessage: "Traiter le nez ameliore l'asthme. Lavage nasal quotidien + spray corticoide.", source: "GINA 2024, ARIA" },
      action: { title: "Lavage nasal", description: "Faites un lavage nasal au serum physiologique. Geste simple qui aide beaucoup.", duration: "3 min" },
    },
    { day: 20, theme: "Signaux d'alerte", phase: 'consolider',
      content: { title: "Quand consulter ?", body: "**Urgence 15/112 :**\n- Essoufflement au repos, ne peut pas parler\n- Bronchodilatateur inefficace\n- Levres/ongles bleutes\n- Confusion\n\n**Consultez rapidement :**\n- Secours > 2x/semaine\n- Reveils nocturnes reguliers\n- Crise severe recente\n\n**Consultez annuellement :** pneumologue ou allergologue.", keyMessage: "Secours > 2x/semaine = asthme non controle. Consultez pour adapter le traitement.", source: "GINA 2024" },
      action: { title: "Preparer sa trousse", description: "Plan 3 zones + medicaments + numeros urgences.", duration: "5 min" },
    },
    { day: 21, theme: "Bilan final", phase: 'consolider',
      content: { title: "21 jours - bravo !", body: "Vous avez termine.\n\n**Ce que vous emportez :**\n- Le traitement de fond comme pilier quotidien\n- Un plan d'action 3 zones\n- L'exercice en securite\n- La respiration nasale\n- Un environnement interieur optimise\n\nL'asthme se controle. Avec les bons gestes, votre vie n'a aucune limite.\n\nRemplissez le questionnaire final.", keyMessage: "L'asthme bien controle = aucune limite. Continuez votre traitement de fond.", source: "GINA 2024" },
      action: { title: "Remplir le bilan final", description: "Questionnaire de fin de cure.", duration: "3 min" },
    },
  ],
};
