import type { ParcoursContent } from './types';

export const bpcoParcours: ParcoursContent = {
  slug: 'bpco',
  title: 'BPCO',
  subtitle: 'Respirer, bouger, reprendre',
  description: '21 jours pour mieux respirer et reprendre le controle.',
  icon: 'pulmonie',
  proInstrument: 'koos-ps',
  proIntro: "Quel degre de difficulte avez-vous pour les activites suivantes, a cause de votre essoufflement ?",
  days: [
    { day: 1, theme: "Comprendre la BPCO", phase: 'comprendre',
      content: { title: "Vos poumons : ce qui se passe", body: "La BPCO est une maladie chronique des poumons ou les bronches se retrecissent progressivement. L'air entre mais sort difficilement.\n\n**Ce que c'est :**\n- Une obstruction progressive des voies aeriennes\n- Toux chronique, expectorations, essoufflement\n- 90% des cas sont lies au tabac\n\nL'exercice adapte est **aussi efficace que les medicaments** pour ameliorer la qualite de vie et reduire les exacerbations.", keyMessage: "La BPCO n'est pas une fatalite. L'arret du tabac + l'exercice changent l'evolution.", source: "GOLD 2024, HAS BPCO" },
      action: { title: "Marche lente - 3 minutes", description: "Marchez 3 minutes a votre rythme. Si vous etes essouffle, ralentissez mais ne vous arretez pas. Echelle d'essoufflement : restez a 3-4/10.", duration: "3 min" },
    },
    { day: 2, theme: "L'arret du tabac", phase: 'comprendre',
      content: { title: "Le seul traitement qui ralentit la maladie", body: "L'arret du tabac est **LA priorite n1** dans la BPCO.\n\n**Ce qui change a l'arret :**\n- 48h : les bronches commencent a se dilater\n- 1 mois : la toux et les expectorations diminuent\n- 3-9 mois : la capacite respiratoire augmente de 10%\n- 1 an : risque d'exacerbation reduit de moitie", keyMessage: "L'arret du tabac est le traitement n1. Meme tard, meme apres des decennies.", source: "GOLD 2024, Cochrane Smoking cessation COPD" },
      action: { title: "Respiration levres pincees - 3 min", description: "Inspirez par le nez (2s), puis expirez LENTEMENT par la bouche avec les levres pincees (4-6s). 10 cycles.", duration: "3 min" },
    },
    { day: 3, theme: "Respirer efficacement", phase: 'comprendre',
      content: { title: "Les techniques respiratoires qui changent tout", body: "Dans la BPCO, l'air reste piege dans les poumons. Les techniques respiratoires aident a vider l'air piege.\n\n**Levres pincees (PLB) :**\nInspirez nez 2s - expirez bouche levres pincees 4-6s.\n\n**Respiration diaphragmatique :**\nAssis, main sur le ventre. Inspirez en gonflant le ventre. Expirez en rentrant le ventre.", keyMessage: "Levres pincees a chaque effort. Inspirez au repos, expirez a l'effort.", source: "GOLD 2024, Pulmonary rehab evidence" },
      action: { title: "Respiration diaphragmatique - 5 min", description: "Assis, main sur le ventre. Inspirez nez en gonflant le ventre. Expirez levres pincees en rentrant le ventre. 10 cycles lents.", duration: "5 min" },
    },
    { day: 4, theme: "L'exercice qui soigne", phase: 'comprendre',
      content: { title: "La rehabilitation respiratoire", body: "La rehabilitation respiratoire combine exercice + education.\n\n**Preuves (Cochrane 2023) :**\n- Reduit l'essoufflement\n- Ameliore la capacite a l'effort\n- Reduit les hospitalisations de 40%\n- Ameliore la qualite de vie autant que les medicaments\n\n**L'exercice adapte BPCO :**\n- Marche fractionnee (3 min marche, 1 min repos)\n- Renforcement des jambes\n- Exercices des bras\n- Toujours avec levres pincees a l'effort", keyMessage: "L'exercice reduit les hospitalisations de 40%. Plus efficace que beaucoup de medicaments.", source: "Cochrane Pulmonary Rehab 2023, GOLD 2024" },
      action: { title: "Marche fractionnee - 8 min", description: "Marchez 3 min - repos assis 1 min - marchez 3 min - repos 1 min. Levres pincees pendant la marche. Essoufflement max 4/10.", duration: "8 min" },
    },
    { day: 5, theme: "Traitements complets", phase: 'comprendre',
      content: { title: "Medicaments + exercice + autogestion", body: "**Medicaments :**\n- Bronchodilatateurs inhales\n- Corticoides inhales si exacerbations frequentes\n- Verifiez votre technique d'inhalation avec votre pharmacien\n\n**Exercice :**\n- Marche : objectif 30 min/jour\n- Renforcement : se lever de chaise, monter des marches\n- Bras : levees laterales avec bouteilles d'eau\n\n**Autogestion :**\n- Plan d'action ecrit\n- Vaccination a jour\n- Eviter pollution et fumee passive", keyMessage: "Inhalateurs bien utilises + exercice quotidien + plan d'action = la triade gagnante.", source: "GOLD 2024, HAS BPCO" },
      action: { title: "Levers de chaise - 5 fois", description: "Assis sur une chaise sans accoudoirs. Levez-vous sans les mains, en soufflant levres pincees. 5 fois. Repos 30s entre chaque.", duration: "3 min" },
    },
    { day: 6, theme: "Cure thermale et BPCO", phase: 'comprendre',
      content: { title: "L'air thermal et l'eau", body: "La cure thermale offre un environnement particulier pour la BPCO :\n\n- L'eau thermale en inhalation humidifie les bronches\n- La piscine thermale permet l'exercice dans un air chaud et humide\n- L'encadrement medical securise la reprise d'activite\n- Le cadre favorise l'arret du tabac\n\nEn piscine : la pression de l'eau sur le thorax aide a expirer.", keyMessage: "L'eau chaude + l'air humide + l'exercice encadre = un tremplin pour vos poumons.", source: "Thermal respiratory evidence" },
      action: { title: "Exercice en piscine", description: "Marche dans l'eau 5 min + levees de bras sous l'eau 10x. Levres pincees.", duration: "7 min" },
    },
    { day: 7, theme: "Bilan semaine 1", phase: 'comprendre',
      content: { title: "Ce que vous avez appris", body: "Semaine 1 terminee !\n\n- La BPCO se stabilise avec les bons gestes\n- L'arret du tabac = traitement n1\n- Levres pincees = technique de base a chaque effort\n- L'exercice reduit les hospitalisations de 40%\n- La technique d'inhalation doit etre verifiee\n\nSemaine 2 : exercices progressifs, gestion des exacerbations.", keyMessage: "Levres pincees + marche fractionnee + inhalateurs bien utilises.", source: "Synthese GOLD/Cochrane" },
      action: { title: "Marche bilan - 10 min", description: "Marche 3+1+3+1+3 min. Comparez avec J1.", duration: "11 min" },
      hasMiniPro: true,
      quiz: [
        { question: "Quel est le seul traitement qui ralentit la progression ?", options: ["Les inhalateurs", "L'arret du tabac", "Les antibiotiques"], correctIndex: 1, explanation: "L'arret du tabac est le seul traitement qui ralentit la perte de capacite respiratoire." },
        { question: "Comment reduire l'essoufflement immediatement ?", options: ["Respirer vite par la bouche", "Levres pincees (inspir nez 2s, expir bouche 4-6s)", "Retenir sa respiration"], correctIndex: 1, explanation: "La technique des levres pincees reduit l'essoufflement immediatement en vidant l'air piege." },
      ],
    },
    { day: 8, theme: "Votre programme d'exercices", phase: 'agir',
      content: { title: "Endurance + renforcement + bras", body: "**Programme BPCO :**\n- Endurance : marche fractionnee, objectif 20-30 min/jour\n- Renforcement jambes : levers de chaise, montee de marches\n- Bras : levees laterales avec bouteilles d'eau (500ml)\n- Respiration : levres pincees pendant CHAQUE effort\n\n**Regle de l'essoufflement :** restez a 3-4/10. Si > 5/10 ralentissez. Si > 7/10 arretez.", keyMessage: "Endurance + renforcement + bras. Levres pincees a chaque effort.", source: "GOLD 2024" },
      action: { title: "Circuit - 12 min", description: "Marche 4 min + repos 1 min + levers chaise 8x + repos 1 min + bras bouteilles 10x + repos 1 min + marche 4 min. Levres pincees.", duration: "12 min" },
    },
    { day: 9, theme: "Renforcement musculaire", phase: 'agir',
      content: { title: "Des jambes fortes = moins d'essoufflement", body: "Des jambes plus fortes = moins de demande en oxygene = moins d'essoufflement pour le meme effort.\n\n**Exercices jambes :**\n- Levers de chaise : 3x8\n- Montee de marche : 10 marches, repos, 10 marches\n- Extensions de genou assis : jambe tendue 5s, 10x chaque", keyMessage: "Des jambes fortes consomment moins d'oxygene. Resultat : moins d'essoufflement.", source: "Cochrane Pulmonary Rehab 2023" },
      action: { title: "Renforcement jambes - 8 min", description: "Levers chaise 3x8 (repos 30s) + extensions genou 10x chaque + montee 10 marches aller-retour. Levres pincees.", duration: "8 min" },
    },
    { day: 10, theme: "Exercices des bras", phase: 'agir',
      content: { title: "Pourquoi travailler les bras dans la BPCO ?", body: "Les activites des bras sont parmi les plus essoufflantes dans la BPCO. Les muscles des bras partagent les muscles respiratoires accessoires.\n\nExercices avec bouteilles d'eau (500ml) :\n- Levees laterales 10x\n- Levees frontales 10x\n- Biceps curl 10x\n\nToujours levres pincees.", keyMessage: "Les bras 'volent' de l'air. Les entrainer reduit l'essoufflement dans les gestes quotidiens.", source: "GOLD 2024, Upper limb training evidence" },
      action: { title: "Circuit bras - 5 min", description: "Avec 2 bouteilles 500ml : levees laterales 10x + levees frontales 10x + biceps 10x. Levres pincees. Repos 30s entre chaque serie.", duration: "5 min" },
    },
    { day: 11, theme: "Gerer les exacerbations", phase: 'agir',
      content: { title: "Reconnaitre et agir face a une crise", body: "Une exacerbation = aggravation soudaine de l'essoufflement, de la toux et/ou des expectorations.\n\n**Signaux d'alerte :**\n- Essoufflement plus important\n- Expectorations jaunes/vertes\n- Fievre\n- Sifflement thoracique\n\n**Plan d'action :**\n- Bronchodilatateur de secours\n- Position assise penchee en avant\n- Levres pincees\n- Si pas d'amelioration en 20 min -> medecin\n- Si detresse severe -> 15/112", keyMessage: "Expectorations jaunes/vertes + essoufflement accru = agir vite. 15/112 si detresse.", source: "GOLD 2024, HAS Exacerbations BPCO" },
      action: { title: "Ecrire votre plan d'action", description: "Notez : signes d'alerte, medicament de secours, position de soulagement, numero du medecin, quand appeler le 15.", duration: "5 min" },
    },
    { day: 12, theme: "Economie d'energie", phase: 'agir',
      content: { title: "Faire plus avec moins de souffle", body: "**Techniques d'economie d'energie :**\n- Fractionnez les activites\n- Asseyez-vous pour les taches\n- Preparez tout avant de commencer\n- Expirez levres pincees pendant chaque effort\n- Utilisez un chariot/caddie\n- Habillez-vous assis", keyMessage: "Fractionnez, asseyez-vous, preparez. C'est de l'intelligence respiratoire.", source: "OT for COPD, GOLD 2024" },
      action: { title: "Identifier 2 taches a adapter", description: "Notez 2 adaptations concretes (ex : repasser assis, cuisine en 2 sessions).", duration: "5 min" },
    },
    { day: 13, theme: "Sommeil et BPCO", phase: 'agir',
      content: { title: "Bien dormir avec la BPCO", body: "**Conseils :**\n- Dormez en position semi-assise (2-3 oreillers)\n- Bronchodilatateur du soir avant le coucher\n- Piece aeree mais pas froide\n- Evitez les repas copieux le soir\n- Inhalation de serum physiologique le soir\n\nSi reveil essouffle la nuit -> parler au medecin (possible apnee du sommeil).", keyMessage: "Position semi-assise + bronchodilatateur du soir + piece aeree.", source: "GOLD 2024" },
      action: { title: "Routine soir - 5 min", description: "5 min de respiration diaphragmatique au lit, position semi-assise (2 oreillers).", duration: "5 min" },
    },
    { day: 14, theme: "Bilan semaine 2", phase: 'agir',
      content: { title: "Mi-parcours", body: "Deux semaines !\n\n- Programme complet (endurance + jambes + bras)\n- Plan d'action exacerbation pret\n- Techniques d'economie d'energie\n- Sommeil adapte\n\nComparez : marchez-vous plus longtemps ?", keyMessage: "Mi-parcours. Vos poumons s'adaptent a l'effort.", source: "Synthese" },
      action: { title: "Circuit complet - 15 min", description: "Marche 5 min + levers chaise 3x8 + bras 10x3 + marche 5 min. Levres pincees.", duration: "15 min" },
      hasMiniPro: true,
      quiz: [
        { question: "Quelle position soulage l'essoufflement ?", options: ["Allonge a plat", "Assis penche en avant", "Debout bras croises"], correctIndex: 1, explanation: "Assis penche en avant, coudes sur les genoux, optimise le travail du diaphragme." },
      ],
    },
    { day: 15, theme: "Plan post-cure", phase: 'consolider',
      content: { title: "Votre programme pour la suite", body: "**Post-cure BPCO :**\n- Marche : 30 min/jour (fractionnee si besoin)\n- Renforcement : levers chaise + bras, 3x/semaine\n- Levres pincees : a CHAQUE effort\n- Bronchodilatateurs bien utilises\n- Plan d'action exacerbation accessible\n- Rehabilitation respiratoire prescrite (remboursee)", keyMessage: "Demandez une rehabilitation respiratoire a votre medecin. C'est rembourse.", source: "GOLD 2024" },
      action: { title: "3 objectifs", description: "Ex : 'Marche 20 min/jour', 'Rehab respiratoire prescrite', 'Vaccination a jour'.", duration: "5 min" },
    },
    { day: 16, theme: "Autogestion", phase: 'consolider',
      content: { title: "Reconnaitre, agir, prevenir", body: "L'autogestion reduit les hospitalisations de 30% (Cochrane 2021).\n\n**Les 3 piliers :**\n- Reconnaitre les signaux d'aggravation\n- Agir selon le plan d'action\n- Prevenir (vaccination, eviter la pollution, exercice regulier)\n\nVotre plan d'action doit etre affiche chez vous.", keyMessage: "Autogestion = -30% hospitalisations. Affichez votre plan d'action.", source: "Cochrane Self-management COPD 2021" },
      action: { title: "Afficher le plan d'action", description: "Imprimez ou recopiez votre plan d'action. Collez-le dans la cuisine. Montrez-le a un proche.", duration: "5 min" },
    },
    { day: 17, theme: "Activite physique adaptee", phase: 'consolider',
      content: { title: "Bouger malgre l'essoufflement", body: "**Excellentes :**\n- Marche (la base)\n- Velo stationnaire\n- Aquagym\n- Tai-chi\n\n**A adapter :**\n- Randonnee (restez bas en altitude)\n- Jardinage (fractionne)\n\n**A eviter :**\n- Exercice par grand froid\n- Altitude > 1500m sans avis medical\n- Pollution/pollen fort", keyMessage: "Velo stationnaire = dosage precis. Marche = la base. Evitez le froid vif.", source: "GOLD 2024" },
      action: { title: "Tester une activite", description: "Essayez le velo stationnaire ou l'aquagym. Avec levres pincees.", duration: "15-20 min" },
    },
    { day: 18, theme: "Nutrition et BPCO", phase: 'consolider',
      content: { title: "Manger pour respirer", body: "**Conseils :**\n- Repas fractionnes (5-6 petits repas)\n- Proteines suffisantes\n- Hydratation 1,5L/jour\n- Pas de surpoids ni de maigreur\n- Eviter les boissons gazeuses (ballonnement -> gene respiratoire)", keyMessage: "Petits repas frequents + proteines + hydratation. Evitez les repas copieux.", source: "GOLD 2024, Nutrition COPD" },
      action: { title: "1 changement alimentaire", description: "Fractionnez un repas en 2 (ex : diner leger + collation 2h apres).", duration: "5 min" },
    },
    { day: 19, theme: "Stress et essoufflement", phase: 'consolider',
      content: { title: "L'anxiete amplifie l'essoufflement", body: "Le stress cree un cercle vicieux : anxiete -> respiration rapide -> sensation d'etouffement -> panique.\n\n**Techniques :**\n- Levres pincees (votre outil n1)\n- Coherence cardiaque adaptee : inspir nez 3s, expir levres pincees 5s\n- Position de soulagement : assis, penche en avant\n- Parler a quelqu'un", keyMessage: "Anxiete -> essoufflement -> panique. Levres pincees + position assise brisent le cercle.", source: "GOLD 2024" },
      action: { title: "Coherence cardiaque adaptee - 5 min", description: "Inspir nez 3s, expir levres pincees 5s. 5 minutes.", duration: "5 min" },
    },
    { day: 20, theme: "Signaux d'alerte", phase: 'consolider',
      content: { title: "Urgences respiratoires", body: "**Appelez le 15/112 si :**\n- Essoufflement severe qui ne s'ameliore pas\n- Levres ou ongles bleutes (cyanose)\n- Confusion ou somnolence\n- Douleur thoracique\n\n**Consultez rapidement si :**\n- Fievre + expectorations jaunes/vertes\n- Gonflement des chevilles\n- Essoufflement qui s'aggrave progressivement", keyMessage: "Levres bleues, confusion, douleur thoracique = 15/112 immediatement.", source: "GOLD 2024" },
      action: { title: "Preparer sa trousse", description: "Plan d'action + medicaments de secours + numero medecin + 15 affiche.", duration: "5 min" },
    },
    { day: 21, theme: "Bilan final", phase: 'consolider',
      content: { title: "21 jours - bravo !", body: "Vous avez termine votre parcours.\n\n**Ce que vous emportez :**\n- Levres pincees comme reflexe\n- Un programme d'exercice complet\n- Un plan d'action pour les exacerbations\n- Des techniques d'economie d'energie\n\nVos poumons sont plus resistants. Continuez l'exercice - c'est votre meilleur medicament.\n\nRemplissez le questionnaire final.", keyMessage: "L'exercice est votre meilleur medicament. Continuez.", source: "GOLD 2024" },
      action: { title: "Remplir le bilan final", description: "Questionnaire de fin de cure.", duration: "3 min" },
    },
  ],
};
