import type { ParcoursContent } from './types';

export const insuffisanceVeineuseParcours: ParcoursContent = {
  slug: 'insuffisance-veineuse',
  title: 'Insuffisance veineuse',
  subtitle: 'Soulager, activer, prevenir',
  description: '21 jours pour des jambes plus legeres.',
  icon: 'jambes',
  proInstrument: 'koos-ps',
  proIntro: "Quel degre de difficulte avez-vous pour les activites suivantes, a cause de vos jambes ?",
  days: [
    { day: 1, theme: "Comprendre vos jambes", phase: 'comprendre',
      content: { title: "L'insuffisance veineuse expliquee", body: "L'insuffisance veineuse, c'est quand les veines de vos jambes n'arrivent plus a remonter le sang vers le coeur. Les valvules fonctionnent mal, le sang stagne.\n\n**Symptomes :**\n- Jambes lourdes, surtout le soir\n- Gonflements (oedemes) des chevilles\n- Varices visibles\n- Demangeaisons\n- Sensation de chaleur ou de brulure\n\n**Ce qui aggrave :** station debout, chaleur, surpoids, sedentarite.\n**Ce qui soulage :** marche (la pompe du mollet !), compression, elevation, eau froide.", keyMessage: "Vos mollets sont le moteur de retour veineux. Les activer = des jambes plus legeres.", source: "ESVS 2022, HAS Maladie Veineuse" },
      action: { title: "Pompe du mollet - 20 flexions", description: "Debout, montez sur la pointe des pieds, maintenez 2s, redescendez. 20 fois. Vos mollets pressent les veines et renvoient le sang vers le coeur.", duration: "2 min" },
    },
    { day: 2, theme: "La compression medicale", phase: 'comprendre',
      content: { title: "Bas de compression : votre allie n1", body: "La compression medicale est le traitement de base de l'insuffisance veineuse.\n\n**Classe de compression :**\n- Classe 2 (15-20 mmHg) : le standard\n- Classe 3 (20-36 mmHg) : si oedeme important\n\n**Conseils pratiques :**\n- Enfilez-les LE MATIN AVANT DE VOUS LEVER\n- Retirez-les le soir au coucher\n- Pas de plis\n- Lavage quotidien\n\nLa compression est remboursee sur prescription.", keyMessage: "Bas de compression chaque matin AVANT de se lever. Classe 2 minimum.", source: "ESVS 2022, Cochrane Compression" },
      action: { title: "Verifier vos bas", description: "Avez-vous des bas de compression ? Sont-ils a la bonne taille ? Ont-ils moins de 6 mois ? Si non, demandez une prescription.", duration: "5 min" },
    },
    { day: 3, theme: "La pompe du mollet", phase: 'comprendre',
      content: { title: "Vos mollets : le coeur de vos jambes", body: "Les veines des jambes n'ont pas de pompe propre. C'est la contraction des muscles des mollets qui propulse le sang vers le haut.\n\n**Si vous restez immobile :** le sang stagne -> jambes lourdes.\n**Si vous marchez :** les mollets se contractent -> le sang remonte.\n\nC'est pourquoi la marche est le meilleur traitement et la station debout immobile le pire ennemi.\n\n**Exercice de base :** monter sur la pointe des pieds. 20x toutes les heures.", keyMessage: "Les mollets sont le 'second coeur'. Activez-les toutes les heures.", source: "ESVS 2022, Physiologie veineuse" },
      action: { title: "Pompe + marche - 5 min", description: "20 pointes de pieds + marche 3 min + 20 pointes de pieds. Sentez-vous la difference ?", duration: "5 min" },
    },
    { day: 4, theme: "Chaleur et veines", phase: 'comprendre',
      content: { title: "La chaleur dilate, le froid tonifie", body: "Les veines se dilatent a la chaleur et se contractent au froid.\n\n**A eviter :**\n- Bains tres chauds (> 37C)\n- Chauffage au sol\n- Exposition au soleil prolongee sur les jambes\n- Cire chaude pour l'epilation\n\n**Ce qui soulage :**\n- Jet d'eau froide sur les jambes en fin de douche (30s)\n- Marche dans l'eau fraiche\n- Gel froid veinotonique le soir", keyMessage: "Finissez chaque douche par un jet froid sur les jambes. 30 secondes suffisent.", source: "ESVS 2022, HAS Maladie Veineuse" },
      action: { title: "Jet froid - 30 secondes", description: "En fin de douche, passez le jet d'eau froide sur vos jambes de bas en haut, 15 secondes chaque jambe.", duration: "1 min" },
    },
    { day: 5, theme: "Traitements", phase: 'comprendre',
      content: { title: "Ce qui marche pour les veines", body: "**Prouve :**\n- Compression medicale - traitement n1\n- Exercice (marche, pompe du mollet) - traitement n2\n- Elevation des jambes 15-20 min/jour\n- Perte de poids si surpoids\n\n**Aide moderee :**\n- Veinotoniques (Daflon, Ginkor)\n- Jet froid\n- Cure thermale\n\n**Traitements specifiques (avis medical) :**\n- Sclerotherapie\n- Laser endoveineux\n- Chirurgie (stripping)", keyMessage: "Compression + marche = le socle. Les veinotoniques aident mais ne suffisent pas.", source: "ESVS 2022, HAS" },
      action: { title: "Marche - 10 min", description: "Marche 10 min a bon rythme. Les mollets travaillent a chaque pas. Compression portee.", duration: "10 min" },
    },
    { day: 6, theme: "Cure thermale et veines", phase: 'comprendre',
      content: { title: "Les soins thermaux pour vos jambes", body: "La cure thermale voies veineuses offre :\n\n- **Bain avec douche sous-marine** : active le retour veineux\n- **Couloir de marche** : alternance chaud/froid\n- **Cataplasmes de boue** : exercice vasculaire\n- **Mobilisation en piscine** : exercices en decharge\n\nLe benefice dure 3-6 mois. Pour le maintenir : compression + marche + jet froid quotidien.", keyMessage: "La cure est un entrainement vasculaire intensif. Continuez compression + marche apres.", source: "SFP, Thermal veineux evidence" },
      action: { title: "Exercices en piscine", description: "Marche dans l'eau 5 min + pompe du mollet 20x + pedalage sur place 2 min. La pression de l'eau comprime naturellement les veines.", duration: "8 min" },
    },
    { day: 7, theme: "Bilan semaine 1", phase: 'comprendre',
      content: { title: "Ce que vous avez appris", body: "Semaine 1 !\n\n- Les mollets = votre second coeur\n- Compression chaque matin avant de se lever\n- Marche = le meilleur traitement\n- Jet froid en fin de douche\n- La cure entraine vos veines\n\nSemaine 2 : exercices cibles, habitudes quotidiennes.", keyMessage: "Compression + marche + jet froid = le trio gagnant au quotidien.", source: "Synthese ESVS/HAS" },
      action: { title: "Bilan - pompe + marche + jet froid", description: "Pompe 20x + marche 10 min + jet froid 30s. Comparez avec J1.", duration: "12 min" },
      hasMiniPro: true,
      quiz: [
        { question: "Quel est le 'coeur' des jambes ?", options: ["Le genou", "Les cuisses", "Les mollets"], correctIndex: 2, explanation: "Les mollets propulsent le sang veineux vers le haut a chaque contraction." },
        { question: "La compression veineuse doit etre enfilee :", options: ["Le matin avant de se lever", "Le soir avant de dormir", "Seulement en cas de douleur"], correctIndex: 0, explanation: "Le matin, les veines sont moins dilatees. La compression est plus efficace posee tot." },
        { question: "Quel geste aggrave l'insuffisance veineuse ?", options: ["La marche quotidienne", "La station debout prolongee sans bouger", "La surelevation des jambes"], correctIndex: 1, explanation: "Rester debout immobile empeche la pompe musculaire de fonctionner." },
      ],
    },
    { day: 8, theme: "Exercices cibles", phase: 'agir',
      content: { title: "5 exercices pour le retour veineux", body: "**Les 5 exercices :**\n- Pompe du mollet debout (20x)\n- Flexion/extension des pieds assis (20x)\n- Pedalage allonge (velo dans les vides, 30s)\n- Marche sur la pointe des pieds (1 min)\n- Elevation des jambes contre le mur (5 min)\n\n3x/jour si possible : matin, midi, soir.", keyMessage: "5 exercices, 5 min, 3x/jour. Plus c'est frequent, mieux c'est.", source: "ESVS 2022" },
      action: { title: "Circuit veineux - 7 min", description: "Pompe 20x + flexions pieds assis 20x + pedalage 30s + marche pointes 1 min + elevation mur 5 min.", duration: "7 min" },
    },
    { day: 9, theme: "Renforcer les mollets", phase: 'agir',
      content: { title: "Des mollets forts = un meilleur retour veineux", body: "Le renforcement des mollets augmente la puissance de la pompe veineuse.\n\n**Progression :**\n- Semaine 1 : pompe 2 pieds, 20x\n- Semaine 2 : pompe 1 pied (alternance), 10x chaque\n- Semaine 3 : pompe 1 pied sur une marche, 10x chaque\n\n**Aussi excellent :** montee d'escaliers.", keyMessage: "Des mollets plus forts = une pompe veineuse plus puissante.", source: "ESVS 2022, Physiotherapy" },
      action: { title: "Pompe progressive - 5 min", description: "Pompe 2 pieds 15x + pompe 1 pied 8x chaque + montee 10 marches x 2.", duration: "5 min" },
    },
    { day: 10, theme: "Au travail et au quotidien", phase: 'agir',
      content: { title: "Les habitudes anti-jambes lourdes", body: "**Au travail (debout) :**\n- Compression obligatoire\n- Pompe du mollet toutes les 30 min\n- Reposer un pied sur un repose-pied\n- Pas de talons hauts > 4 cm ni de chaussures plates\n\n**Au travail (assis) :**\n- Ne pas croiser les jambes\n- Flexions de pieds toutes les 30 min\n- Se lever et marcher 2 min toutes les heures\n\n**En avion/train (> 4h) :**\n- Compression classe 2 obligatoire\n- Marcher toutes les 2h\n- Flexions de pieds assis toutes les 30 min", keyMessage: "Compression portee + pompe toutes les 30 min = jambes legeres meme au travail.", source: "ESVS 2022, HAS" },
      action: { title: "Identifier 2 habitudes", description: "Quelles situations aggravent vos jambes ? Notez 2 changements concrets (alarme 30 min, repose-pieds).", duration: "5 min" },
    },
    { day: 11, theme: "Surelevation des jambes", phase: 'agir',
      content: { title: "La gravite a votre service", body: "Surelever les jambes 15-20 min aide le sang a redescendre vers le coeur.\n\n**Comment :**\n- Allonge, jambes contre le mur (90) ou sur un coussin\n- 15-20 min, 1-2x/jour\n- Les pieds doivent etre AU-DESSUS du coeur\n\n**La nuit :**\n- Surelevez le pied du lit de 10-15 cm\n- Pas d'oreiller sous les genoux\n\nPratique simple, gratuite, et efficace.", keyMessage: "Jambes contre le mur 15 min le soir. Pieds au-dessus du coeur.", source: "ESVS 2022" },
      action: { title: "Jambes contre le mur - 10 min", description: "Allonge, fesses contre le mur, jambes a la verticale. Restez 10 min. Faites des flexions de pieds toutes les 2 min.", duration: "10 min" },
    },
    { day: 12, theme: "Gerer les poussees", phase: 'agir',
      content: { title: "Quand les jambes gonflent plus que d'habitude", body: "**Plan d'action :**\n- Compression portee toute la journee\n- Surelevation 20 min x 3 dans la journee\n- Jet froid prolonge (1 min chaque jambe)\n- Marche fractionnee (5 min x 4)\n- Eviter la chaleur et la station debout\n\n**Consultez si :**\n- Gonflement d'UNE SEULE jambe, rouge, chaud, douloureux -> phlébite -> URGENCE\n- Ulcere veineux\n- Saignement d'une varice", keyMessage: "UNE jambe gonflée, rouge et chaude = phlebite possible. Consultez EN URGENCE.", source: "ESVS 2022" },
      action: { title: "Ecrire plan poussee", description: "Notez les etapes + le signal d'alerte phlebite (1 jambe rouge chaude = urgence).", duration: "5 min" },
    },
    { day: 13, theme: "Poids et veines", phase: 'agir',
      content: { title: "Chaque kilo compte pour vos veines", body: "Le surpoids augmente la pression dans les veines des jambes et aggrave l'insuffisance veineuse.\n\nUne perte de 5-10% du poids reduit significativement les symptomes.\n\nLa cure thermale est un moment ideal : vous bougez, vous mangez mieux, vous etes encadre.", keyMessage: "Perdre du poids soulage la pression dans vos veines. La cure est le moment.", source: "ESVS 2022" },
      action: { title: "Marche - 15 min", description: "Marche 15 min a bon rythme. Compression portee. Les mollets travaillent.", duration: "15 min" },
    },
    { day: 14, theme: "Bilan semaine 2", phase: 'agir',
      content: { title: "Mi-parcours", body: "Deux semaines !\n\n- 5 exercices de retour veineux\n- Habitudes quotidiennes (pompe 30 min, surelevation)\n- Signaux d'alerte phlebite\n- Compression bien portee\n\nVos jambes sont-elles moins lourdes le soir ?", keyMessage: "Mi-parcours. La regularite paie.", source: "Synthese" },
      action: { title: "Circuit complet - 10 min", description: "5 exercices + surelevation 5 min.", duration: "10 min" },
      hasMiniPro: true,
      quiz: [
        { question: "Quel exercice active le mieux la pompe veineuse ?", options: ["Les montees sur pointes de pieds", "Les abdominaux", "Les etirements du dos"], correctIndex: 0, explanation: "Les montees sur pointes contractent les mollets et propulsent le sang vers le coeur." },
        { question: "L'eau thermale aide le retour veineux grace a :", options: ["Sa temperature elevee", "Son gout mineral", "La pression hydrostatique"], correctIndex: 2, explanation: "La pression de l'eau sur les jambes comprime les veines et aide le sang a remonter." },
        { question: "Quelle temperature de douche est recommandee pour les jambes ?", options: ["Tres chaude", "Tiede a fraiche, jet du bas vers le haut", "Alternance chaud-froid rapide"], correctIndex: 1, explanation: "L'eau fraiche contracte les veines et stimule le retour veineux." },
      ],
    },
    { day: 15, theme: "Plan post-cure", phase: 'consolider',
      content: { title: "Votre routine veineuse", body: "**Quotidien :**\n- Compression du matin au soir\n- Pompe du mollet toutes les heures\n- Marche 30 min/jour\n- Jet froid en fin de douche\n- Surelevation 15 min le soir", keyMessage: "Compression + marche + jet froid + surelevation = vos 4 piliers.", source: "ESVS 2022" },
      action: { title: "3 objectifs", description: "Ex : 'Compression chaque jour', 'Marche 30 min', 'Jet froid chaque douche'.", duration: "5 min" },
    },
    { day: 16, theme: "Mode de vie", phase: 'consolider',
      content: { title: "Adaptations durables", body: "**Vetements :** pas de vetements serres a la taille/cuisses.\n**Chaussures :** 3-4 cm de talon (ni plat ni haut).\n**Chaleur :** eviter bains > 37C, chauffage au sol.\n**Position :** pas de jambes croisees, alterner assis/debout.\n**Voyage :** compression + marche toutes les 2h.", keyMessage: "Pas de serre, pas de trop chaud, pas d'immobile. Bougez.", source: "ESVS 2022" },
      action: { title: "1 adaptation", description: "Identifiez 1 changement (chaussures, habitude de croiser les jambes, temperature de bain).", duration: "5 min" },
    },
    { day: 17, theme: "Activite physique", phase: 'consolider',
      content: { title: "Les meilleurs sports pour vos veines", body: "**Excellents :** marche, natation, aquagym, velo, marche nordique.\n**Bons :** danse, yoga, golf.\n**A eviter :** musculation lourde, sauna prolonge, sports sur sol dur avec pietinement.\n\nL'aquagym est ideale : la pression de l'eau comprime naturellement les veines + exercice des mollets.", keyMessage: "Aquagym = compression naturelle + exercice. L'ideal pour vos veines.", source: "ESVS 2022" },
      action: { title: "Tester l'aquagym", description: "Essayez l'aquagym : marche dans l'eau + pompe du mollet + pedalage.", duration: "15 min" },
    },
    { day: 18, theme: "Alimentation", phase: 'consolider',
      content: { title: "Manger pour vos veines", body: "**Ce qui aide :**\n- Hydratation 1,5L/jour\n- Fibres (eviter la constipation)\n- Flavonoides (fruits rouges, agrumes)\n- Poids raisonnable\n\n**A limiter :** sel excessif (retention d'eau -> oedeme).", keyMessage: "Hydratation + fibres + fruits rouges + peu de sel. Pas de constipation.", source: "SFP recommendations" },
      action: { title: "1 changement", description: "Boire 1,5L/jour, fruits rouges au gouter, reduire le sel.", duration: "5 min" },
    },
    { day: 19, theme: "Ete et veines", phase: 'consolider',
      content: { title: "Survivre a la chaleur", body: "L'ete est la pire saison pour les veines (chaleur dilate).\n\n**Strategies :**\n- Compression meme en ete (modeles fins existent)\n- Jet froid plusieurs fois par jour\n- Brumisateur sur les jambes\n- Marche tot le matin ou le soir\n- Surelevation prolongee si grosse chaleur\n- Pas d'exposition soleil directe sur les jambes", keyMessage: "L'ete : compression fine + jet froid + marche au frais + surelevation.", source: "SFP, HAS" },
      action: { title: "Preparer l'ete", description: "Commandez des bas de compression fins pour l'ete. Preparez un brumisateur.", duration: "5 min" },
    },
    { day: 20, theme: "Signaux d'alerte", phase: 'consolider',
      content: { title: "Quand consulter", body: "**URGENCE :**\n- UNE jambe gonflée + rouge + chaude + douloureuse -> phlebite -> 15/112\n- Saignement d'une varice qui ne s'arrete pas -> comprimer + 15\n\n**Consultation rapide :**\n- Ulcere veineux\n- Modification cutanee (peau brune, induree)\n- Douleur de mollet intense au repos\n\n**Suivi regulier :** phlebologue ou angiologue 1x/an.", keyMessage: "1 jambe rouge, chaude, gonflée = phlebite possible = urgence.", source: "ESVS 2022" },
      action: { title: "Preparer sa trousse", description: "Plan poussee + signal phlebite + numero medecin.", duration: "5 min" },
    },
    { day: 21, theme: "Bilan final", phase: 'consolider',
      content: { title: "21 jours - bravo !", body: "Vous avez termine.\n\n**Ce que vous emportez :**\n- La pompe du mollet comme reflexe\n- La compression chaque matin\n- Le jet froid chaque soir\n- La surelevation quotidienne\n- 5 exercices de retour veineux\n\nVos veines ne guerissent pas mais vos symptomes se controlent. Avec ces gestes quotidiens, vos jambes resteront legeres.\n\nRemplissez le questionnaire final.", keyMessage: "Compression + pompe + jet froid + surelevation = jambes legeres durablement.", source: "ESVS 2022" },
      action: { title: "Remplir le bilan final", description: "Questionnaire de fin de cure.", duration: "3 min" },
    },
  ],
};
