import type { ParcoursContent } from './types';

export const otitesEnfantParcours: ParcoursContent = {
  slug: 'otites-repetition-enfant',
  title: 'Otites à répétition (enfant)',
  subtitle: 'Comprendre, prévenir, accompagner',
  description: '21 jours pour mieux gérer les otites de votre enfant.',
  icon: '👶',
  proInstrument: 'koos-ps',
  proIntro: "Quel degré de difficulté avez-vous pour les activités suivantes, à cause des otites de votre enfant ?",
  days: [
    // ========== SEMAINE 1 : COMPRENDRE ==========
    { day: 1, theme: "Comprendre les otites", phase: 'comprendre',
      content: { title: "Pourquoi les enfants font des otites", body: "Les otites sont très fréquentes chez les enfants : 80% des enfants auront au moins une otite avant 3 ans. On parle d'otites à répétition quand il y en a plus de 3 par an.\n\n**Pourquoi les enfants ?**\n• La trompe d'Eustache (tube entre l'oreille et la gorge) est plus courte et plus horizontale chez l'enfant → les microbes remontent plus facilement\n• Le système immunitaire est encore immature\n• Les végétations (adénoïdes) sont souvent grosses et bloquent la ventilation\n\n**Ce qui aggrave :**\n• Crèche/collectivité (exposition aux virus)\n• Tabac passif (LE facteur évitable n°1)\n• Tétine prolongée après 6 mois\n• Biberons en position couchée\n• Pollution intérieure\n\nPendant ces 3 semaines, vous apprendrez à réduire la fréquence des otites et à mieux accompagner votre enfant.", keyMessage: "Les otites sont fréquentes et normales. Le tabac passif est le facteur évitable n°1.", source: "NICE OME 2022, HAS Otite" },
      action: { title: "Lavage de nez de votre enfant", description: "Le lavage de nez est le geste préventif n°1 chez l'enfant. Avec un spray de sérum physiologique, 2-3 pressions par narine, 2×/jour minimum (plus si enrhumé). Mouchez ou aspirez après.", duration: "3 min" },
    },
    { day: 2, theme: "Le tabac passif", phase: 'comprendre',
      content: { title: "Objectif zéro fumée pour votre enfant", body: "Le tabac passif est le facteur de risque évitable le plus important pour les otites à répétition.\n\n**Ce que le tabac fait :**\n• Paralyse les cils de la muqueuse (le nez ne se nettoie plus)\n• Augmente l'inflammation de la trompe d'Eustache\n• Affaiblit les défenses immunitaires locales\n• Double le risque d'otites\n\n**Même dehors ou sur le balcon :** les particules restent sur les vêtements, les cheveux, les meubles (tabac résiduel).\n\n**Solution :** aucun adulte ne fume à l'intérieur ou en présence de l'enfant. Idéalement : arrêt du tabac (3989, médecin).\n\nC'est la mesure qui a le plus grand impact sur les otites — plus que tout médicament.", keyMessage: "Zéro fumée autour de l'enfant. C'est plus efficace que n'importe quel médicament.", source: "NICE 2022, AAP 2013" },
      action: { title: "Bilan tabac à la maison", description: "Y a-t-il un fumeur à la maison ? Si oui, est-il possible de ne jamais fumer à l'intérieur et de changer de vêtements avant de prendre l'enfant ?", duration: "5 min" },
    },
    { day: 3, theme: "Le lavage de nez", phase: 'comprendre',
      content: { title: "Le geste n°1 : un nez propre", body: "Un enfant qui a le nez bouché ventile mal ses oreilles. La trompe d'Eustache ne s'ouvre pas bien, le liquide stagne, les microbes prolifèrent → otite.\n\n**Le lavage de nez :**\n• Sérum physiologique en dosettes ou spray\n• 2-3×/jour en prévention, 5-6×/jour si enrhumé\n• Position : bébé sur le côté, spray dans la narine du haut\n• Aspirer avec un mouche-bébé si besoin après\n\n**Chez l'enfant plus grand (> 2 ans) :**\n• Apprendre à se moucher (boucher une narine, souffler par l'autre)\n• Spray ou seringue de lavage\n\nC'est simple, gratuit, et ça réduit les otites.", keyMessage: "Un nez propre = des oreilles en bonne santé. Lavez 2-3×/jour minimum.", source: "HAS Otite, NICE 2022" },
      action: { title: "Pratiquer le lavage", description: "Faites un lavage de nez à votre enfant (ou aidez-le à se moucher correctement). Observez : le nez coule-t-il plus facilement après ?", duration: "3 min" },
    },
    { day: 4, theme: "Xylitol et hygiène", phase: 'comprendre',
      content: { title: "Prévention au quotidien", body: "**Le xylitol :**\n• Sucre naturel qui EMPÊCHE les bactéries d'adhérer aux muqueuses\n• Sous forme de chewing-gum (> 4 ans), sirop, ou pastilles\n• 5×/jour après les repas et collations\n• Peut réduire les otites de 25% (Cochrane)\n\n**Lavage des mains :**\n• Après la crèche/école, avant les repas, après s'être mouché\n• Eau + savon 20 secondes (pas de gel hydroalcoolique systématique)\n\n**Limiter les virus :**\n• Aérer les pièces 10 min/jour\n• Éviter les contacts avec des enfants très enrhumés\n• Humidifier si air sec (40-60% d'humidité)", keyMessage: "Xylitol 5×/jour + lavage des mains + nez propre = prévention efficace.", source: "Cochrane Xylitol, HAS" },
      action: { title: "Essayer le xylitol", description: "Si votre enfant a > 2 ans : essayez un sirop au xylitol après les repas. Si > 4 ans : chewing-gum xylitol après chaque repas. Vérifiez en pharmacie.", duration: "5 min" },
    },
    { day: 5, theme: "Traitements", phase: 'comprendre',
      content: { title: "Ce qui marche (et ce qui ne marche pas)", body: "**Prouvé :**\n• Lavage de nez quotidien — prévention\n• Vaccination antipneumococcique (calendrier vaccinal) — réduit les otites bactériennes\n• Vaccination antigrippale annuelle — réduit les otites de 30%\n• Xylitol — prévention modeste mais réelle\n\n**Aide :**\n• Cure thermale ORL — améliore la ventilation et réduit les récidives\n• Adénoïdectomie si végétations obstructives (chirurgie, sur avis ORL)\n• Aérateurs trans-tympaniques (yoyos) si otite séreuse persistante > 3 mois avec perte auditive\n\n**PAS de preuve :**\n• Homéopathie\n• Ostéopathie crânienne\n• Oligothérapie\n\n**Les antibiotiques** ne sont PAS systématiques : la majorité des otites guérissent seules en 48-72h. Antibiotique si < 2 ans, ou si pas d'amélioration après 48h.", keyMessage: "La plupart des otites guérissent sans antibiotique en 48-72h. Lavage de nez = prévention n°1.", source: "HAS Otite 2017, NICE 2022, AAP 2013" },
      action: { title: "Vérifier les vaccinations", description: "Vérifiez le carnet de santé : pneumocoque (Prevenar) à jour ? Grippe annuelle faite ? Parlez-en au médecin.", duration: "5 min" },
    },
    { day: 6, theme: "Cure thermale et otites", phase: 'comprendre',
      content: { title: "Les soins thermaux ORL pour votre enfant", body: "La cure thermale ORL pour les enfants comprend :\n\n• **Aérosols soniques** — microparticules qui pénètrent dans la trompe d'Eustache\n• **Douche nasale** — lavage professionnel des fosses nasales\n• **Insufflation tubaire** — ventile l'oreille moyenne (méthode de Politzer)\n• **Inhalation** — humidifie la muqueuse\n\nLes études montrent une réduction de 30-50% des épisodes d'otites dans l'année suivant la cure.\n\nLe bénéfice est maximal si le lavage de nez quotidien est maintenu après la cure.", keyMessage: "La cure réduit les otites de 30-50% l'année suivante si le lavage est maintenu.", source: "Thermal ORL enfant evidence" },
      action: { title: "Observer les soins", description: "Pendant les soins de votre enfant, observez sa réaction. Aidez-le à se moucher efficacement après. Encouragez-le — les soins peuvent être impressionnants pour un petit.", duration: "5 min" },
    },
    { day: 7, theme: "Bilan semaine 1", phase: 'comprendre',
      content: { title: "Ce que vous avez appris", body: "Semaine 1 !\n\n• Les otites sont normales et fréquentes chez l'enfant\n• Tabac passif = facteur évitable n°1\n• Lavage de nez = prévention n°1\n• Xylitol peut aider\n• Antibiotiques pas systématiques\n• La cure réduit les récidives\n\nSemaine 2 : gestion des épisodes et habitudes.", keyMessage: "Nez propre + zéro fumée + xylitol = votre kit anti-otites.", source: "Synthèse NICE/HAS/AAP" },
      action: { title: "Lavage + évaluation", description: "Faites le lavage de nez + évaluez : votre enfant respire-t-il mieux par le nez ?", duration: "5 min" },
      hasMiniPro: true,
      quiz: [
        { question: "Quel est le facteur évitable n°1 des otites ?", options: ["Le froid", "Le tabac passif", "La crèche"], correctIndex: 1, explanation: "Le tabac passif double le risque d'otites. C'est le facteur le plus facilement éliminable." },
        { question: "Faut-il toujours des antibiotiques pour une otite ?", options: ["Oui, toujours", "Non, la majorité guérissent seules en 48-72h", "Seulement si fièvre"], correctIndex: 1, explanation: "La majorité des otites guérissent sans antibiotique. On attend 48-72h sauf si < 2 ans ou symptômes sévères." },
      ],
    },

    // ========== SEMAINE 2 : AGIR ==========
    { day: 8, theme: "Gérer un épisode d'otite", phase: 'agir',
      content: { title: "Que faire quand votre enfant a mal à l'oreille", body: "**Immédiatement :**\n• Paracétamol (dose poids, pas d'ibuprofène systématique)\n• Lavage de nez +++ (5-6×/jour)\n• Chaleur locale (compresse tiède sur l'oreille)\n• Position semi-assise pour dormir\n\n**Consulter si :**\n• Enfant < 2 ans\n• Fièvre > 38,5°C persistante > 48h\n• Écoulement de l'oreille (otorrhée)\n• Douleur très intense, enfant inconsolable\n• Pas d'amélioration après 48h\n\n**NE PAS METTRE** de gouttes dans l'oreille sans avis médical.", keyMessage: "Paracétamol + lavage de nez. Consultez si < 2 ans, fièvre > 48h, ou écoulement.", source: "HAS Otite 2017" },
      action: { title: "Préparer un kit otite", description: "À la maison : paracétamol (dose poids notée), sérum physiologique, mouche-bébé, thermomètre. Tout au même endroit.", duration: "5 min" },
    },
    { day: 9, theme: "Allaitement et immunité", phase: 'agir',
      content: { title: "Les facteurs de protection", body: "**Facteurs protecteurs prouvés :**\n• Allaitement maternel (> 3 mois réduit le risque)\n• Vaccination à jour (pneumocoque + grippe)\n• Lavage de nez régulier\n• Xylitol\n• Pas de tabac passif\n\n**Facteurs de risque :**\n• Collectivité (crèche > garderie > garde individuelle)\n• Tétine après 6 mois (augmente le reflux vers l'oreille)\n• Biberons en position couchée\n• Fratrie nombreuse (plus de virus circulants)\n\nVous ne pouvez pas tout contrôler. Concentrez-vous sur ce qui est faisable : lavage de nez, pas de fumée, vaccination.", keyMessage: "Concentrez-vous sur ce que vous pouvez : nez propre, pas de fumée, vaccins.", source: "AAP 2013, NICE 2022" },
      action: { title: "Checklist prévention", description: "Cochez : □ Lavage nez 2×/jour □ Pas de tabac □ Vaccins à jour □ Xylitol essayé □ Tétine < 6 mois □ Pas de biberon couché", duration: "3 min" },
    },
    { day: 10, theme: "Le moucher", phase: 'agir',
      content: { title: "Apprendre à se moucher (un vrai défi !)", body: "Se moucher efficacement s'apprend entre 2 et 4 ans. C'est un apprentissage important.\n\n**Technique :**\n1. Boucher une narine avec le doigt\n2. Souffler fort par l'autre narine dans un mouchoir\n3. Changer de côté\n\n**Astuces pour apprendre :**\n• Jeu : souffler une plume/bougie avec le nez\n• Montrer l'exemple (mouchez-vous devant l'enfant)\n• Féliciter chaque tentative\n• Commencer par souffler par le nez (bouche fermée)\n\nEn attendant, le mouche-bébé fait le travail.", keyMessage: "Apprendre à se moucher = investissement santé pour toute la vie.", source: "HAS, Pédiatrie" },
      action: { title: "Exercice de mouchage", description: "Jeu : demandez à votre enfant de souffler une plume/petit papier posé sur la table avec le nez (bouche fermée). C'est le premier pas vers le mouchage.", duration: "5 min" },
    },
    { day: 11, theme: "Otite séreuse", phase: 'agir',
      content: { title: "Quand du liquide reste dans l'oreille", body: "L'otite séreuse (otite séromuqueuse, OSM) = du liquide reste derrière le tympan sans infection. C'est la suite fréquente des otites aiguës.\n\n**Symptômes :**\n• Sensation d'oreille bouchée\n• Baisse d'audition (l'enfant n'entend pas bien, fait répéter)\n• Retard de langage possible si prolongé\n\n**Évolution :**\n• 90% se résorbent spontanément en 3 mois\n• Lavage de nez aide à ventiler\n• Cure thermale aide (insufflation tubaire)\n\n**Si > 3 mois avec perte auditive :** avis ORL → aérateurs (yoyos) possibles.", keyMessage: "L'otite séreuse se résorbe en 3 mois dans 90% des cas. Si baisse d'audition → ORL.", source: "NICE OME 2022" },
      action: { title: "Test simple d'audition", description: "Dans une pièce calme, parlez doucement à 2 mètres derrière votre enfant. Entend-il ? Chuchotez. Fait-il répéter souvent ? Si doute, demandez un test auditif.", duration: "3 min" },
    },
    { day: 12, theme: "Sommeil et oreilles", phase: 'agir',
      content: { title: "Bien dormir avec des otites récurrentes", body: "**Position :** surélever légèrement la tête (coussin supplémentaire ou cales sous le matelas). Favorise le drainage.\n**Lavage avant le coucher :** nez propre = mieux respirer la nuit.\n**Humidité :** chambre à 18-20°C, humidité 40-60%.\n**Doudou propre :** laver régulièrement (acariens).", keyMessage: "Tête légèrement surélevée + nez propre avant le coucher.", source: "Pédiatrie consensus" },
      action: { title: "Routine du soir", description: "Ce soir : lavage de nez + position légèrement surélevée. Observez si l'enfant dort mieux.", duration: "5 min" },
    },
    { day: 13, theme: "Quand consulter l'ORL", phase: 'agir',
      content: { title: "Les signaux qui nécessitent un spécialiste", body: "**Consultez l'ORL si :**\n• > 3 otites en 6 mois ou > 4 en 12 mois\n• Otite séreuse > 3 mois avec baisse auditive\n• Retard de langage\n• Otorrhée (écoulement) récidivante\n• Otites malgré prévention bien conduite\n\n**L'ORL pourra :**\n• Évaluer les végétations (adénoïdes)\n• Faire un audiogramme\n• Proposer des aérateurs (yoyos) si nécessaire\n• Proposer une adénoïdectomie si végétations obstructives", keyMessage: "> 3 otites en 6 mois ou baisse d'audition > 3 mois = consultez l'ORL.", source: "NICE 2022, HAS" },
      action: { title: "Bilan", description: "Comptez : combien d'otites dans les 6 derniers mois ? Si > 3, prenez RDV ORL.", duration: "3 min" },
    },
    { day: 14, theme: "Bilan semaine 2", phase: 'agir',
      content: { title: "Mi-parcours", body: "Deux semaines !\n\n• Kit otite prêt\n• Facteurs protecteurs identifiés\n• Mouchage en cours d'apprentissage\n• Otite séreuse comprise\n• Critères de consultation ORL connus\n\nVotre enfant a-t-il le nez plus propre ? Dort-il mieux ?", keyMessage: "Mi-parcours. La prévention est en marche.", source: "Synthèse" },
      action: { title: "Routine complète", description: "Lavage nez + xylitol + vérifier environnement (tabac, humidité).", duration: "10 min" },
      hasMiniPro: true,
      quiz: [
        { question: "À partir de combien d'otites consulter l'ORL ?", options: ["1 seule otite", "> 3 en 6 mois ou > 4 en 12 mois", "Seulement si opération"], correctIndex: 1, explanation: "Plus de 3 otites en 6 mois ou 4 en 12 mois justifie un avis ORL spécialisé." },
      ],
    },

    // ========== SEMAINE 3 : CONSOLIDER ==========
    { day: 15, theme: "Plan post-cure", phase: 'consolider',
      content: { title: "Votre routine anti-otites", body: "**Quotidien :**\n• Lavage de nez 2-3×/jour (plus si enrhumé)\n• Xylitol après les repas\n• Pas de tabac passif\n• Apprendre à se moucher\n\n**Saisonnier :**\n• Vaccination grippe avant l'hiver\n• Cure thermale ORL 1×/an si > 3 otites/an", keyMessage: "Lavage quotidien + xylitol + zéro fumée = votre bouclier anti-otites.", source: "NICE 2022, HAS" },
      action: { title: "3 objectifs", description: "Ex : « Lavage nez 3×/jour », « Zéro tabac maison », « RDV ORL si > 3 otites ».", duration: "5 min" },
    },
    { day: 16, theme: "Crèche et collectivité", phase: 'consolider',
      content: { title: "Réduire les virus en collectivité", body: "La collectivité est le premier facteur de risque (inévitable souvent).\n\n**Ce que vous pouvez faire :**\n• Lavage de nez AVANT et APRÈS la crèche\n• Lavage des mains à l'arrivée à la maison\n• Vêtements adaptés (pas de surchauffe)\n• Garde individuelle ou petite structure si otites très fréquentes (si possible)\n• Signaler les otites à répétition au médecin de crèche", keyMessage: "Lavage de nez avant ET après la crèche. Lavage des mains en rentrant.", source: "AAP 2013" },
      action: { title: "Routine crèche", description: "Demain : lavage de nez avant de partir + lavage de nez + mains en rentrant.", duration: "3 min" },
    },
    { day: 17, theme: "Activité physique de l'enfant", phase: 'consolider',
      content: { title: "Bouger renforce les défenses", body: "L'activité physique régulière renforce le système immunitaire de l'enfant.\n\n**Recommandations :**\n• Au moins 1h d'activité physique/jour (jeux, marche, vélo)\n• Jeux extérieurs +++ (air frais > air intérieur recyclé)\n• Natation : oui, mais rincer le nez au sérum physiologique après (chlore)\n\n**Attention :** si otite séreuse avec perte auditive → pas de plongée. Natation en surface OK.", keyMessage: "1h d'activité/jour dehors + lavage de nez après la piscine.", source: "WHO recommandations enfants" },
      action: { title: "Sortie extérieure — 30 min", description: "Emmenez votre enfant jouer dehors 30 min. L'air frais est meilleur pour les voies aériennes que l'air intérieur.", duration: "30 min" },
    },
    { day: 18, theme: "Alimentation de l'enfant", phase: 'consolider',
      content: { title: "Nourrir les défenses immunitaires", body: "**Ce qui aide :**\n• Alimentation variée (fruits, légumes, protéines)\n• Vitamine D (souvent supplémentée chez l'enfant — vérifiez avec le médecin)\n• Hydratation suffisante (fluidifie les sécrétions)\n• Pas d'excès de sucre (favorise l'inflammation)\n\n**Le reflux gastro-œsophagien (RGO)** peut favoriser les otites chez le nourrisson → biberons en position semi-assise, pas couché.", keyMessage: "Alimentation variée + vitamine D + hydratation. Biberon semi-assis, jamais couché.", source: "AAP 2013, Nutrition pédiatrique" },
      action: { title: "Vérifier la vitamine D", description: "Votre enfant prend-il sa supplémentation en vitamine D ? Vérifiez avec le carnet de santé.", duration: "3 min" },
    },
    { day: 19, theme: "L'audition de votre enfant", phase: 'consolider',
      content: { title: "Surveiller pour protéger le langage", body: "Les otites à répétition peuvent entraîner une baisse auditive temporaire qui peut retarder le langage.\n\n**Signes d'alerte :**\n• L'enfant fait souvent répéter\n• Il monte le son de la télévision\n• Il ne réagit pas quand on l'appelle\n• Retard de langage pour son âge\n• Il parle fort\n\nSi vous observez ces signes → audiogramme (test indolore). Mieux vaut tester « pour rien » que rater un problème.", keyMessage: "Si votre enfant fait souvent répéter → demandez un test d'audition. C'est simple et indolore.", source: "NICE OME 2022" },
      action: { title: "Observer l'audition", description: "Cette semaine, observez : votre enfant entend-il quand vous l'appelez dans une autre pièce ? Répond-il quand vous chuchotez ? Monte-t-il le son ?", duration: "5 min" },
    },
    { day: 20, theme: "Urgences ORL enfant", phase: 'consolider',
      content: { title: "Quand c'est urgent", body: "**Consultez en urgence si :**\n• Gonflement derrière l'oreille (mastoïdite — oreille décollée, rougeur)\n• Fièvre élevée + douleur intense + enfant prostré\n• Paralysie du visage (rare)\n• Vertige chez l'enfant\n• Écoulement persistant > 2 semaines malgré traitement\n\n**La mastoïdite** est la complication la plus importante à reconnaître : l'oreille semble « poussée vers l'avant » avec un gonflement rouge derrière. C'est une URGENCE hospitalière.", keyMessage: "Gonflement rouge derrière l'oreille = mastoïdite = urgence hospitalière.", source: "NICE 2022, HAS" },
      action: { title: "Reconnaître la mastoïdite", description: "Recherchez une image de mastoïdite (oreille décollée, gonflement rouge derrière). C'est le seul signe d'urgence vitale à connaître.", duration: "3 min" },
    },
    { day: 21, theme: "Bilan final", phase: 'consolider',
      content: { title: "21 jours — bravo !", body: "Vous avez terminé.\n\n**Ce que vous emportez :**\n• Le lavage de nez comme réflexe quotidien\n• Zéro tabac passif\n• Xylitol après les repas\n• Un kit otite prêt à la maison\n• Les signaux d'alerte (mastoïdite, audition)\n\nLes otites diminuent naturellement avec l'âge (la trompe d'Eustache grandit). En attendant, votre prévention fait une vraie différence.\n\nRemplissez le questionnaire final.", keyMessage: "Les otites diminuent avec l'âge. Votre prévention accélère l'amélioration.", source: "NICE 2022, HAS" },
      action: { title: "Remplir le bilan final", description: "Questionnaire de fin de cure.", duration: "3 min" },
    },
  ],
};
